### ISSUE TITLE
'Failed to write reg' error

### ISSUE THREAD

**Issue by ghost** [elementary/triage#10]
I found my laptop taking longer than usual to shut down, and when pressing the <kbd>&#8595;</kbd> key during the plymouth shutdown screen I noticed a message reading `[   17.918501] failed to write reg 28b4 wait reg 28c6` (not those exact numbers). The relevant part of `dmesg`'s output can be seen below:
<details><summary>`dmesg`</summary>
[    4.884956] ath10k_pci 0000:01:00.0: unsupported HTC service id: 1536
[    6.778426] failed to write reg 28b4 wait reg 28c6
[    8.386396] failed to write reg 1a6f4 wait reg 1a706
[    9.917763] wlp1s0: authenticate with 84:a1:d1:a0:c0:65
[    9.962922] wlp1s0: send auth to 84:a1:d1:a0:c0:65 (try 1/3)
[    9.965238] wlp1s0: authenticated
[    9.968205] wlp1s0: associate with 84:a1:d1:a0:c0:65 (try 1/3)
[    9.971326] wlp1s0: associate with 84:a1:d1:a0:c0:65 (try 2/3)
[    9.974449] wlp1s0: associate with 84:a1:d1:a0:c0:65 (try 3/3)
[    9.977575] wlp1s0: association with 84:a1:d1:a0:c0:65 timed out
[   10.106164] failed to write reg 28b4 wait reg 28c6
[   10.167490] wlp1s0: authenticate with 84:a1:d1:a0:c0:64
[   10.216858] wlp1s0: send auth to 84:a1:d1:a0:c0:64 (try 1/3)
[   10.218539] wlp1s0: authenticated
[   10.220178] wlp1s0: associate with 84:a1:d1:a0:c0:64 (try 1/3)
[   10.223724] wlp1s0: RX AssocResp from 84:a1:d1:a0:c0:64 (capab=0x411 status=0 aid=3)
[   10.226154] wlp1s0: associated
[   10.226321] ath: EEPROM regdomain: 0x833a
[   10.226323] ath: EEPROM indicates we should expect a country code
[   10.226325] ath: doing EEPROM country->regdmn map search
[   10.226326] ath: country maps to regdmn code: 0x37
[   10.226328] ath: Country alpha2 being used: GB
[   10.226329] ath: Regpair used: 0x37
[   10.226331] ath: regdomain 0x833a dynamically updated by country element
[   10.257480] IPv6: ADDRCONF(NETDEV_CHANGE): wlp1s0: link becomes ready
[   11.710442] failed to write reg 1a6f4 wait reg 1a706
[   13.041141] [drm] SADs count is: 0, don't need to read it
[   13.330446] failed to write reg 28b4 wait reg 28c6
[   14.938576] failed to write reg 1a6f4 wait reg 1a706
[   17.918501] failed to write reg 28b4 wait reg 28c6
[   19.526591] failed to write reg 1a6f4 wait reg 1a706
[   21.138453] failed to write reg 28b4 wait reg 28c6
[   22.750534] failed to write reg 1a6f4 wait reg 1a706
[   23.018244] rfkill: input handler disabled
[   23.132228] Bluetooth: RFCOMM TTY layer initialized
[   23.132245] Bluetooth: RFCOMM socket layer initialized
[   23.132256] Bluetooth: RFCOMM ver 1.11
[   24.966147] failed to write reg 28b4 wait reg 28c6
[   26.293035] rfkill: input handler enabled
[   26.578457] failed to write reg 1a6f4 wait reg 1a706
[   32.430044] rfkill: input handler disabled
[   34.618614] failed to write reg 28b4 wait reg 28c6
[   36.233248] failed to write reg 1a6f4 wait reg 1a706
[   44.387257] acer_wmi: Unknown function number - 8 - 1
[   51.680823] failed to write reg 28b4 wait reg 28c6
[   53.374027] failed to write reg 1a6f4 wait reg 1a706
[   55.083088] failed to write reg 28b4 wait reg 28c6
[   56.800081] failed to write reg 1a6f4 wait reg 1a706
[  441.642292] failed to write reg 28b4 wait reg 28c6
[  443.294429] failed to write reg 1a6f4 wait reg 1a706
[  444.942495] failed to write reg 28b4 wait reg 28c6
[  446.570643] failed to write reg 1a6f4 wait reg 1a706
[  601.937925] failed to write reg 28b4 wait reg 28c6
[  603.546072] failed to write reg 1a6f4 wait reg 1a706
[  605.177489] failed to write reg 28b4 wait reg 28c6
[  606.841042] failed to write reg 1a6f4 wait reg 1a706
</details>
I left out the start of the log as the message only occurred in this end section.

System details:
![Screenshot from 2020-01-24 16-25-38](https://user-images.githubusercontent.com/35624360/73085176-30b77e80-3ec6-11ea-8ea2-004789c726a8.png)

**Comment by calslate** [comment]
Closing as this issue seems to have fixed itself 🤔️

**Comment by calslate** [comment]
Reopening: happened once again

**Comment by ghost** [comment]
Related issue: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1838176 (In fact, I'll close this issue as it's obviously an upstream problem)
