### ISSUE TITLE
System freeze related to `hdy_carousel_box`?

### ISSUE THREAD

**Issue by lukors** [elementary/triage#100]
I'm sorry for this vague issue, but this seemed like the best place for it.

My system freezes at least ~2 times per day. In Pop!_OS that did not happen. I'm really enjoying elementary OS and really don't want to switch back, but I will have to unless I can fix this issue. So I'll try to give as much information as I can, and I'm hoping to get help from you to diagnose the issue so it can be fixed.

### System info
![Skärmbild från 2021-12-07 14-11-31](https://user-images.githubusercontent.com/1719884/145035470-9e34a47e-d951-426c-ac54-1d1e4c8d3307.png)
![Skärmbild från 2021-12-07 14-11-47](https://user-images.githubusercontent.com/1719884/145035483-97681b95-0daa-4e34-b6f1-c8086edcde9a.png)

### Facts
- I can't press `ctrl alt F2` to get a prompt after a freeze
- It wasn't freezing from the beginning, it started at some point, but I don't know when exactly.
- They happen when I'm not doing anything in particular, most recently I was on the phone and was just slightly moving my mouse cursor over my Signal window when it froze.
- They seem related to web rendering, I believe Signal uses web rendering, it has happened in Firefox often and in Chromium. I can't remember it happening in something other than a web rendered application, but I'll keep an eye out for it.
- It seems to not happen in Web, if that means anything, maybe uses other web rendering?
- I have stayed away as much as I can from doing anything non-standard, so staying away from .deb files and `apt-get`, and installing anything that is like "low level" in the system.
- I tried getting the System76 power management stuff working at one point to change the charge thresholds on my battery. I couldn't get it to work and I tried uninstalling all that since. I don't recall that being connected to the freezing, but could be.

### `/var/log/syslog` output
I'm getting a huge block of these:
```text
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@
```

Don't know if that means anything. Those seem to be in the log right when the freeze happens.

Before that block of those, I often see a lot of this stuff:
```text
Dec  7 13:40:01 lemp10 io.elementary.a[1880]: hdy_carousel_box_get_position: assertion 'HDY_IS
_CAROUSEL_BOX (self)' failed
Dec  7 13:40:01 lemp10 io.elementary.a[1880]: hdy_carousel_box_get_n_pages: assertion 'HDY_IS_
CAROUSEL_BOX (self)' failed
Dec  7 13:40:01 lemp10 io.elementary.a[1880]: hdy_carousel_box_get_position: assertion 'HDY_IS
_CAROUSEL_BOX (self)' failed
Dec  7 13:40:01 lemp10 io.elementary.a[1880]: hdy_carousel_box_get_nth_child: assertion 'HDY_I
S_CAROUSEL_BOX (self)' failed
Dec  7 13:40:01 lemp10 io.elementary.a[1880]: hdy_carousel_box_scroll_to: assertion 'HDY_IS_CA
ROUSEL_BOX (self)' failed
Dec  7 13:40:06 lemp10 io.elementary.a[1880]: hdy_carousel_box_get_position: assertion 'HDY_IS
_CAROUSEL_BOX (self)' failed
Dec  7 13:40:06 lemp10 io.elementary.a[1880]: hdy_carousel_box_get_n_pages: assertion 'HDY_IS_
CAROUSEL_BOX (self)' failed
Dec  7 13:40:06 lemp10 io.elementary.a[1880]: hdy_carousel_box_get_position: assertion 'HDY_IS
_CAROUSEL_BOX (self)' failed
Dec  7 13:40:06 lemp10 io.elementary.a[1880]: hdy_carousel_box_get_nth_child: assertion 'HDY_I
S_CAROUSEL_BOX (self)' failed
Dec  7 13:40:06 lemp10 io.elementary.a[1880]: hdy_carousel_box_scroll_to: assertion 'HDY_IS_CA
ROUSEL_BOX (self)' failed
```

The most recent crash has 21 pages of that in my terminal before the `^@^@^@^@^@` stuff, starting at `Dec  7 13:32:58` and ending there at `Dec  7 13:40:06`.

And that's all I've got.

I'm a pretty technical person and highly motivated to get rid of this freezing. Any help to further diagnose the issue or possible solutions is greatly appreciated.

**Comment by vjr** [comment]
Did you manually update your kernel to 5.15 ? If so can you try downgrade back to say 5.13 ?

**Comment by lukors** [comment]
I did not manually update my kernel. I'm guessing that happened when I uninstalled the System76 power management stuff, I assumed it would bring me back to the original kernel (not that I understood it would install a different kernel in the first place), but apparently it installed another one.

I'm assuming the latest kernel for elementary OS is 5.13?

Right after I posted this I randomly found a way to consistently reproduce the locking, which was to visit [this website](https://myfujifilm.se/products/printsClient.html?productTag=category.prints_glossy#/), adding a picture using the purple button, and then waiting less than a minute.

That freeze is no longer happening, and the website works as expected, so I think this solved my freezing issue! Many, many thanks to you @vjr! :pray:

**Comment by Jiangxb8** [comment]
Hello, I am also using pop os system now, and I have encountered the same problem as you. My computer is down almost once every two days. The following is the latest system log:
Oct 17 19:31:49 pop-os io.elementary.a[6729]: hdy_carousel_box_get_n_pages:  assertion 'HDY_IS_CAROUSEL_BOX (self)' failed
Oct 17 19:31:49 pop-os io.elementary.a[6729]: hdy_carousel_box_get_position:  assertion 'HDY_IS_CAROUSEL_BOX (self)' failed
Oct 17 19:31:49 pop-os io.elementary.a[6729]: hdy_carousel_box_get_nth_child:  assertion 'HDY_IS_CAROUSEL_BOX (self)' failed
Oct 17 19:31:49 pop-os io.elementary.a[6729]: hdy_carousel_box_scroll_to: assertion 'HDY_IS_CAROUSEL_BOX (self)' failed
![image](https://github.com/user-attachments/assets/98532f93-8732-448a-88b3-05eae9198b22)

I don't know what caused it. How did you solve it? I really need your help. Thank you so much.

**Comment by lukors** [comment]
I think the problem came because I had accidentally installed a different kernel. The solution for me was to install the kernel that elementary came with.

Sorry for the late response.
