### ISSUE TITLE
Running Lenovo P14s after kernel upgrade/dist upgrade internal screen after grub shows white noise and vertical color lines on right side of screen

### ISSUE THREAD

**Issue by jekabs-milbrets-tet** [elementary/triage#133]
Running Lenovo P14s with amd ryzen pro 7 after kernel upgrade/dist upgrade internal screen after grub shows white noise and vertical color lines on right side of screen. Before grub internal monitor works;

 cat /etc/os-release 
NAME="elementary OS"
VERSION="6.1 Jólnir"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 6.1 Jólnir"
LOGO=distributor-logo
VERSION_ID="6.1"
HOME_URL="https://elementary.io/"
DOCUMENTATION_URL="https://elementary.io/docs/learning-the-basics"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/triage/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=jolnir
UBUNTU_CODENAME=focal

 cat /proc/version
Linux version 5.13.0-27-generic (buildd@lgw01-amd64-045) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022

**Comment by meisenzahl** [comment]
Probably related to https://bugs.launchpad.net/ubuntu/focal/+source/linux-firmware/+bug/1958283

**Comment by jekabs-milbrets-tet** [comment]
Thanks, I`ll look in to this!
