### ISSUE TITLE
Three Fingers Up Gesture May Instead Close an App That Is Being Used 

### ISSUE THREAD

**Issue by Fatih20** [elementary/triage#140]
### What Happened?

I don't know if this is the intended behavior or not but if you are using the three fingers up gesture for the touchpad in a way that is somewhat quick, instead of showing the multitasking view, it has a high likelihood of closing the currently active window. Frankly, this makes me wary of using the gesture to show multitasking view since it might instead close the app I'm currently using.

### Steps to Reproduce

Use three swipe gesture going up that is quick (not gentle).

### Expected Behavior

Just show me my multitasking view.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

![Screenshot from 2022-04-04 00-23-59](https://user-images.githubusercontent.com/51940383/161440272-c6e5d550-4931-4a1b-afc1-9d514903782a.png)

**Comment by davidmhewitt** [comment]
I think this is probably something to do with https://github.com/elementary/gala/issues/975

In the multitasking view, a middle-click will close a window, and a 3 finger tap is interpreted as a middle click.

Does this sound like the same issue?

**Comment by Fatih20** [comment]
> I think this is probably something to do with [elementary/gala#975](https://github.com/elementary/gala/issues/975)
> 
> In the multitasking view, a middle-click will close a window, and a 3 finger tap is interpreted as a middle click.
> 
> Does this sound like the same issue?

Yep I think it is the same issue.

**Comment by davidmhewitt** [comment]
Then I will close this issue as that one is more specific. Feel free to add any additional thoughts or comments on that issue.

Thanks for the report!

**Comment by Fatih20** [comment]
Okay then thanks for pointing that issue out.
