### ISSUE TITLE
Aspect cropping in contextual and dropdown windows

### ISSUE THREAD

**Issue by ask4you2002** [elementary/triage#145]
I had used Elementary OS for too long time ago. Since last versions, I can appreciate that contextual windows (e.g when right clicking on the desktop or selecting from a dropdown window) create a cropping effect and won't disappear till opening the window again.

### Steps to reproduce this cropping effect:

1. Right click on the desktop or click a options menu:
* [clicking on some options menu](https://imgur.com/us5a11z)

* [clicking on desktop](https://imgur.com/5eqBUrD)

2. Closing that menu or opening a new one results in this cropping effect:

* [cropping in options menu](https://imgur.com/8iR62c5)

* [cropping in desktop](https://imgur.com/yOiHXML)

### OS version
* 6.1 (Jólnir)

### Hardware
* I'm using a laptop (Core I7 16gb RAM)

In this case, the images are taken from a Virtual Machine, but this also was hapenning when I had Elementary OS as host OS.
This has nothing to see with themes or whatever and I don't know if this is related to some kind of compatibility somehow. I expect I'm not the only one having this issue and that It will be fixed soon.

**Comment by lenemter** [comment]
Fixed in OS 7
