### ISSUE TITLE
Cmake is not part of elementary-sdk

### ISSUE THREAD

**Issue by 0xfalafel** [elementary/triage#158]
### What Happened?

I installed the package elementary-sdk in elementary Horus.

cmake is a dependency needed to build most elementary package, but it wasn't part of elementary-sdk.

### Steps to Reproduce

1. git clone https://github.com/elementary/videos.git && cd videos
2. sudo apt install elementary-sdk
3. $ meson build --prefix=/usr
```
The Meson build system
Version: 0.61.2
Source dir: /projets/elementary/videos
Build dir: /projets/elementary/videos/build
Build type: native build
Project name: io.elementary.videos
Project version: 2.9.0
C compiler for the host machine: cc (gcc 11.3.0 "cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
C linker for the host machine: cc ld.bfd 2.38
Vala compiler for the host machine: valac (valac 0.56.3)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Configuring Config.vala using configuration
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency clutter-gst-3.0 found: NO (tried pkgconfig)

src/meson.build:1:0: ERROR: Dependency "clutter-gst-3.0" not found, tried pkgconfig
```

### Expected Behavior

cmake should have been installed after running
sudo apt install elementary-sdk

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by davidmhewitt** [comment]
CMake is not required here. This is just meson warning that it can't use cmake to find dependencies.

The actual error is this:
```
src/meson.build:1:0: ERROR: Dependency "clutter-gst-3.0" not found, tried pkgconfig
```

So you're missing the `clutter-gst-3.0` dependency, which is not in the SDK. The SDK only contains dependencies that are common to most/all elementary applications.

You can see the list of required packages to build an app in its README file.
