### ISSUE TITLE
Automated bug report does not work

### ISSUE THREAD

**Issue by daniel-naegele** [elementary/triage#21]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
When an error occurs, the dialog asks me if I want to send it and to remember this decision. I check the remember decision box and click 'Send'. Then another window pops up (See screenshots). If I type the command manually, the same error occurs (See logs). Also settings does not get saved.

### To Reproduce
1. Experience a bug (?) and see the bug report feature
2. Clidk on 'Remember this'
3. Click on 'send'

### Expected behavior
It should work...

### Screenshots or screen recordings
https://imgur.com/a/HltyI5K

### Logs
`$ gdbus call -y -d com.ubuntu.WhoopsiePreferences -o /com/ubuntu/WhoopsiePreferences -m com.ubuntu.WhoopsiePreferences.SetReportCrashes true
Fehler: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name com.ubuntu.WhoopsiePreferences was not provided by any .service files`

## Platform Information
https://imgur.com/a/2Wd64Fy

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by daniel-naegele** [comment]
https://imgur.com/a/1ONQ24l
Ok so this looks really official, I have taken a screenshot. It could be, that I have installed this by installed. As not everyone is able to speak German, I am gonna translate the first 3 lines:
Sorry, »elementary OS 5.1.2« hat einen internen Fehler festgestellt.
Send error report to the developers?
If you encounter any more problems, try restart your comter.

**Comment by danirabbit** [comment]
Closing since this seems to be related to Ubuntu Whoopsie which we don't install by default
