### ISSUE TITLE
Instructions to run with early Wayland support don't seem to work

### ISSUE THREAD

**Issue by TeamPuzel** [elementary/triage#249]
### What Happened?

I was following this wiki: https://github.com/elementary/gala/wiki/Experimenting-with-Wayland

Unfortunately, trying to start the session results in a completely black screen. The instructions seem to be really old, are they still up to date? There's a few ideas for apps I would like to try, but most of them are not portable between X and Wayland; supporting the latter seems more future-proof.

I am not using Nvidia or AMD, I tried everything on a 2015 MacBook Pro with integrated intel graphics, so I wouldn't expect a compatibility issue.

### Steps to Reproduce

1. Follow the steps from the wiki
2. Black screen

### Expected Behavior

I expected lots of issues, but didn't expect it to break completely

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
N/A
```

### Hardware Info

2015 MacBook Pro 13"

**Comment by lenemter** [comment]
Fixed.
