### ISSUE TITLE
EOS with kernel 5.xx failed to start GUI every time,but kernel 6.3.5 is OK.

### ISSUE THREAD

**Issue by 31i45** [elementary/triage#281]
It's very annoying. EOS with kernel 5.xx failed to start GUI every time, I had to fsck the file system several time. But kernel 6.3.5 is OK.

**Comment by danirabbit** [comment]
We use the Ubuntu kernel, so we're reliant on Canonical to provide newer kernels. We should see a 6.x kernel for elementary OS 8 next year, but for now closing as "Out of scope" since this is essentially an upstream issue

**Comment by davidmhewitt** [comment]
As an update on this, Ubuntu has this week switched their HWE kernel to 6.2 in `jammy`.

So the next 7.1 ISO that we release should have a 6.2 kernel.
