### ISSUE TITLE
Increasing font and then decreasing it right away causes static notebook size to not change back

### ISSUE THREAD

**Issue by D0J0P** [elementary/triage#306]
At least in Settings > Desktop > Dock

![Screenrecordfrom2019-07-3112](https://user-images.githubusercontent.com/19495660/62228754-48d19980-b38c-11e9-8bc0-e8891a4fd43a.gif)

**Comment by danirabbit** [comment]
I can't reproduce this anymore. It likely was an old Gtk bug that was fixed
