### ISSUE TITLE
Migrate away from Bountysource

### ISSUE THREAD

**Issue by cassidyjames** [elementary/triage#32]
We've been having reliability issues in the first place, and the site has gone downhill since it was required by a crypto company. We'd like to migrate away from it. To do so, we'll need to retarget any outstanding bounties. We should also explore alternatives, though that's less urgent imho.

There's a hard deadline of **July 1** for their new ToS, so we'll want to sort this out before then.

**Comment by quassy** [comment]
You should probably move fast before losing a couple of hundred dollars (at least from what I see on your Bountysource page).

**Comment by danirabbit** [comment]
Gonna close this because I think we've done everything there is to do there:

- [x] Removed Bountysource from our website
- [x] Requested all bounties to be withdrawn
- [x] Requested an account cash out
- [x] Removed bountysource integration from GitHub
- [x] Wrote a blog post about it

**Comment by cassidyjames** [comment]
Anyone following along here, see: https://blog.elementary.io/goodbye-bountysource-hello-github-sponsors/

**Comment by quassy** [comment]
Cool, last time I checked two days there were many more bounties left, now it's only these two when I use the search function on Bountysource: [Can't set keyboard layout change to alt+shift, ctrl+shift, etc.](https://www.bountysource.com/issues/6720153-can-t-set-keyboard-layout-change-to-alt-shift-ctrl-shift-etc) and [Global Transfers Indicator](https://www.bountysource.com/issues/447345-global-transfers-indicator)
