### ISSUE TITLE
Add support for `System Tray`

### ISSUE THREAD

**Issue by sauntor** [elementary/triage#334]
### Problem

Some apps employs `System Tray` for it's  design purpose, i.e.  `Flameshot`. If there's no `tray`,  some features may be imperfect.
Take `Flameshot` for example,  you can't start a snapshot from the panel via the `tray`.

The community plugin https://github.com/MvBonin/wingpanel-community-indicators can't work well, as for some apps does not shown in it's UI.

### Proposal
By now, many utilities/apps use `System Tray` for their  design purpose.

1. Add the `official` support for `System Tray` on the top panel.
2. Or add an extra area on the dock to simulate it.

**Comment by lenemter** [comment]
elementary OS will not support system tray, see https://github.com/elementary/wingpanel/issues/96
