### ISSUE TITLE
[upstream] LibreOffice read-only dialog

### ISSUE THREAD

**Issue by o-alquimista** [elementary/triage#358]
### What Happened?

This was reported [here](https://github.com/flathub/org.libreoffice.LibreOffice/issues/203).

### Steps to Reproduce

1. Using Firefox flatpak'ed, download a file that LibreOffice will open, and open it from Firefox download history.
> The read-only dialog from LibreOffice appears.
2. Now open the same downloaded file, but using the file manager.
> File opens read-write as expected.

### Expected Behavior

File should open read-write.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

elementary 7.1.
Dell Inspiron 15 3583.
Fresh install. Sideloading some apps from Flathub. Multi-user (1 admin, 1 unprivileged).

**Comment by danirabbit** [comment]
Gonna close this as "out of scope" since it effects apps that aren't made by elementary as well as other operating systems so very likely there isn't anything we can do in any of our code bases to resolve this
