### ISSUE TITLE
Using pantheon on other distributions

### ISSUE THREAD

**Issue by ksharinarayanan** [elementary/triage#382]
Hey, I noticed that a new version has been released with the intention of making it compatible with other distributions ([Release](https://github.com/elementary/session-settings/releases/tag/6.0.0))

But, I don't find any instructions on how to install :(

My current distribution is archcraft (almost pure arch)

Thanks

**Comment by lenemter** [comment]
I think Pantheon is available on arch nowadays, so the issue is fixed.
