### ISSUE TITLE
elementary OS won't shut down, stucks in logo screen.

### ISSUE THREAD

**Issue by dincertekin** [elementary/triage#384]
Hello, I want to use elementary OS and I love it but on my ASUS ROG STRIX G513IE laptop its not booting up correctly and I can't shut it down. There is no errors on screen but I only see ROG logo on my screen. Also I removed other linux kernel(6.2.0-36) and now its booting up correctly. But its still stucks at shutting down.

I don't know what can I do this is my first time on getting this error.
When I ran setup after "Remove installation media" it says: https://i.imgur.com/g9blK8b.jpg
And setup screen looks like this (left-aligned not in center of my screen): https://i.imgur.com/uuLOK87.jpeg

**Comment by dincertekin** [comment]
Hello, I tried using Fedora it works perfectly but still I can't shut down elementary OS 7.1 Horus. It makes me wait till forever.

**Comment by ryonakano** [comment]
> And setup screen looks like this (left-aligned not in center of my screen): https://i.imgur.com/uuLOK87.jpeg

Just leaving a comment that the above point is tracked at elementary/installer#881.

**Comment by dincertekin** [comment]
Thank you. I fixed the problem my own.
If anybody have the same issue, just boot ISO file with "nomodeset" parameter and uncheck automatically install NVIDIA drivers after disk partition on setup.

On first time boot use "nomodeset" parameter again.
After booting first time do sudo apt update and upgrade then install gcc and gcc-12 and install NVIDIA Linux Drivers with "CC=12 sudo ./NVIDIA-Linux-*.run" and rebuild initramfs and autoinstall DKMS.

After all of these steps above I run elementaryOS without any problem.
