### ISSUE TITLE
Desktop freezes occasionally (Juno)

### ISSUE THREAD

**Issue by dillonfagan** [elementary/triage#403]
The desktop will occasionally freeze, where the mouse pointer can still be moved, but all windows are frozen. Also, the status bar (if that's what it's called) loses its transparency (goes black) and cannot be clicked on either. I'm not sure if there's any pattern to this or if it's been happening at random.

**Comment by mikebz** [comment]
I am seeing this as well.  

Linux berger-tower 5.3.0-62-generic elementary/gala#56~18.04.1-Ubuntu SMP Wed Jun 24 16:17:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

    description: Desktop Computer
    product: OptiPlex 7050 (07A1)
    vendor: Dell Inc.
    serial: CLVBJL2
    width: 64 bits

Full config is attached.

[hw.txt](https://github.com/elementary/gala/files/4921728/hw.txt)

**Comment by lenemter** [comment]
Closing because the issue is stale.
