### ISSUE TITLE
Dual display slow down on Juno

### ISSUE THREAD

**Issue by Nikoos** [elementary/triage#404]
Hello Team,

I encounter a strange behaviour on a dual screen configuration (dual NVIDIA GPU GTX960), with a fresh Juno installation : 

When displaying on both screen a full screen video with two different web browser, my second monitor is not able to display smoothly the video.

This behaviour is also present with the same web browser on both screen.

In my case, my first screen displayed Google chrome with a Twitch replay and on the other screen : opera with a 1080p HD youtube video.

To be noted : when I close my  first web browser on my first screen, the second screen continue to play video witch glitches.

I was able to perform multiples tests on differents Ubuntu releases and elementary :

- Ubuntu 18.04.1 LTS : no issue to display 2 videos in a dual display configuration.
- Ubuntu 18.10 :  no issue to display 2 videos in a dual display configuration.
- Elementary OS Loki :  no issue to display 2 videos in a dual display configuration.
- Elementary OS Juno :  slow down on the second monitor to display videos in a dual display configuration.

For the main 3 tests, I use the following tests: 
sudo apt update && sudo apt upgrade -y && sudo ubuntu-driver autoinstall

Best regards,

Nikos

**Comment by felix-andreas** [comment]
I just got a notification because the ticket was moved.

If I remembered correctly, this issue was resolved https://github.com/elementary/gala/pull/540
