### ISSUE TITLE
Ship touchegg and custom configuration

### ISSUE THREAD

**Issue by cassidyjames** [elementary/triage#44]
This may end up being moved from triage to a better home and/or split into multiple issues across repos.

## Problem

We want to ship touchegg with an elementary-default configuration that differs from the upstream. Also, it's not packaged. 

## Proposal

- Package touchegg
- Add touchegg to seeds
- Ship our custom configuration

## Prior Art

We package and ship LibHandy.

**Comment by cassidyjames** [comment]
The configuration I've been using (and I think similar or identical to @danrabbit's config):

https://gist.github.com/cassidyjames/85ff4079572bc07c74dd8a5770972733

**Comment by danirabbit** [comment]
This has now been completed :)
