### ISSUE TITLE
Latest OS 8 daily boots to black screen.

### ISSUE THREAD

**Issue by tnetenbaa** [elementary/triage#445]
### What Happened?

After installation, both on VM and hardware, after installation it takes several minutes for user creation to show up, and after that is finished, you get a black screen. Rebooting just goes back to black screen.

### Steps to Reproduce

1. install.
2.reboot.

### Expected Behavior

No black screen.

### OS Version

Early Access

### Software Version

Latest release (I have run all updates)

**Comment by vjr** [comment]
Just a note that you can (for now) enter your password to login anyway, at least I can, presuming it's just the one user and the password input field is selected by default.

**Comment by vjr** [comment]
Also, could you mention your GPU details?

If I'm not imagining things, it might be the recent fade-in feature to the login screen (greeter) because I also get blank screen on my older AMD RX580 GPU but not on a newer laptop with the AMD 780M iGPU that comes with the 7840U CPU.

**Comment by tnetenbaa** [comment]
Running on 3 different systems, one with an RTX 2060, one with Intel integrated graphics, and one is a VM. Entering my password to login does not work, and attempting to startx via TTY I get a "Oops! Something has gone wrong" screen.

**Comment by tnetenbaa** [comment]
Nice, can't wait to test this in the next daily.
