### ISSUE TITLE
Last update kernel problem

### ISSUE THREAD

**Issue by DAFAVAC** [elementary/triage#447]
The last version kernel "Linux 5.3.0-53-generic"  ,keep the system electic on after of poweoff or reboot also the high temperatures during use. I solved it ,downgrade kernel at  "Linux 5.3.0-51-generic"  and now run without problem.

Sincerely DAFAVAC

**Comment by danirabbit** [comment]
Thanks for your report! Gonna close this since this is about a pretty old kernel version. For future reference, we use the Ubuntu kernel, so if you notice Kernel regressions please file them upstream with Ubuntu in launchpad
