### ISSUE TITLE
Install font family

### ISSUE THREAD

**Issue by claxonberlin** [elementary/triage#47]
## Problem
I'm trying to install a font family without having to go through every font separately.

## Proposal
It would be great if Elementary OS would automatically recognize this and, when double clicking one font, would provide two install buttons: one for single font and one for font family.

**Comment by cassidyjames** [comment]
The Fonts app is provided by GNOME; this should probably be a feature request there: https://gitlab.gnome.org/GNOME/gnome-font-viewer/-/issues
