### ISSUE TITLE
Grub screen cannot be hidden (EOS public beta)

### ISSUE THREAD

**Issue by kalzEOS** [elementary/triage#496]
I have looked into /etc/defaul/grub and the timeout is already set to 0, but every time I reboot, a blue grub screen shows up that doesn't boot automatically. I'd have to hit enter on the first option to boot into the system.
btw, boot time is the quickest I've seen on any other distro. Kudos, guys.

**Comment by gfavaro** [comment]
This also affects the stable release.

**Comment by ryonakano** [comment]
Closing as duplicate of #109
