### ISSUE TITLE
Missing Icons on Dock and in Applications menu

### ISSUE THREAD

**Issue by KerryatCLC** [elementary/triage#531]
### What Happened?

After last Tuesday or Wednesday's update, upon restart, most of the icons on the dock and in the Application menu (and notification and Bluetooth icons) are missing. The app links themselves are still there invisibly, and the name pops up when you hover over them, but no visible Icon. A few are still there, but many are gone. 

### Steps to Reproduce

I installed all updates on a daily basis.

### Expected Behavior

Expected to see all icons, as normal.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Running on a Dell Lattitude 3590 off external SSD.

**Comment by diogopessoa** [comment]
Do you use third party icons?

**Comment by KerryatCLC** [comment]
Not other than those supplied by the few apps I've added, like Libre Office, but those show up.

**Comment by KerryatCLC** [comment]
Fixed. Went into recovery mode and ran fix broken pkgs. Icons reappeared.
