### ISSUE TITLE
Inconsistent mouse pointer

### ISSUE THREAD

**Issue by myhousece** [elementary/triage#575]
### What Happened?

The mouse pointer is showing inconsistency between some applications. I'm not sure if it's just on my machine. I'm currently up to date with the system. Elementary 8.0

### Steps to Reproduce

![1](https://github.com/user-attachments/assets/0a4ce67b-6091-40e3-a769-c233d4b75377)
![2](https://github.com/user-attachments/assets/a9488852-943f-46f3-af52-fc1deb573b09)
![3](https://github.com/user-attachments/assets/b7302ecb-cc6d-47c1-a25d-0e824f5ae37e)
![4](https://github.com/user-attachments/assets/f132916e-1e0a-4039-9cfe-4ab355e264e4)

### Expected Behavior

I'm not sure if it's just on my machine.

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Hardware Info

ROG-Zephyrus-G15-GA503RM
AMD Ryzen 9 6900HS with Radeon Graphics 
AMD® Rembrandt [Radeon 680M]
24 GB memória

**Comment by lenemter** [comment]
Fixed in https://github.com/elementary/gala/pull/2140
