### ISSUE TITLE
[OS 8 RC] In the 'Secure' session, some apps and Titlebars don't use the elementary Stylesheet.

### ISSUE THREAD

**Issue by cyrneko** [elementary/triage#587]
### What Happened?

Upon selecting the 'Secure' / Wayland session, I noticed that anything GTK3 as well as some apps' titlebars were not using the elementaryOS Stylesheet. This affects things like Signal and Vesktop, which don't have their own titlebars by default, as well as [ScreenRec](https://appcenter.elementary.io/com.github.dr_styki.screenrec/) and the LibreWolf Flatpak.

As a side-note, I have only tested this with Flatpaks from Flathub and AppCenter.

### Steps to Reproduce

1. Enable/Switch to the 'secure' session before login
2. Open a GTK3 Application, or one that uses Serverside-Decorations (OS titlebars)
3. Observe issue

### Expected Behavior

The applications should use the elementaryOS stylesheet.

### OS Version

8.x (Early Access)

### Session Type

Secure Session (Wayland)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
Very likely fixed by https://github.com/elementary/default-settings/pull/319
