### ISSUE TITLE
AppCenter & appstream not working properly in Turkish language

### ISSUE THREAD

**Issue by queeup** [elementary/triage#6]
## Describe the bug
Since few months I realize AppCenter not showing Trending and always showing same 2 apps on Recently Updated in Turkish language. Also most of the apps missing from it. English language working as expected.

appstreamcli also not refreshing or showing status.

### To Reproduce
1. Go to System Settings
2. Click on Language & Region
3. Change Language to Turkish (also click apply system wide?)
4. Logout from your session and log back in.
5. Open AppCenter (or just open terminal and try to refresh appstreamcli with Turkish language and print status.)

### Expected behavior
Working like in English. Showing all apps. Showing Trending and all Recently Updated apps in Turkish language.

### Screenshots or screen recordings
![AppCenter in Turkish](https://i.stack.imgur.com/s30QR.png)

### Logs
 - I cut it the logs. If you want to check full logs please [click here](https://gist.github.com/queeup/5a189b86ad3d31ea38d785c0d4da4d7f)

**set Turkish Language:**
```
~ $ G_MESSAGES_DEBUG=all io.elementary.switchboard
(io.elementary.switchboard:21725): GnomeDesktop-DEBUG: 22:23:26.128: Ignoring 'C.UTF-8' as a locale, since it lacks translations
(io.elementary.switchboard:21725): GnomeDesktop-DEBUG: 22:23:26.128: Ignoring 'C.UTF-8' as a locale, since it lacks translations
(io.elementary.switchboard:21725): GnomeDesktop-DEBUG: 22:23:26.131: Ignoring 'C.UTF-8' as a locale, since it lacks translations
** (io.elementary.switchboard:21725): DEBUG: 22:23:26.525: LocaleView.vala:78: reloading Settings widget for language 'en'
** (io.elementary.switchboard:21725): DEBUG: 22:23:40.790: LocaleView.vala:78: reloading Settings widget for language 'tr'
** (io.elementary.switchboard:21725): DEBUG: 22:23:43.535: LocaleSetting.vala:130: Setting user language to 'tr'
** (io.elementary.switchboard:21725): DEBUG: 22:23:43.535: LocaleManager.vala:103: Setting user language to tr
** (io.elementary.switchboard:21725): DEBUG: 22:23:43.784: LocaleSetting.vala:144: Setting user format to 'tr_TR.UTF-8'
** (io.elementary.switchboard:21725): DEBUG: 22:23:43.784: LocaleManager.vala:117: Setting user format to tr_TR.UTF-8
** (io.elementary.switchboard:21725): DEBUG: 22:23:51.364: LocaleSetting.vala:320: Setting system language to 'tr' and format to 'tr_TR.UTF-8'
** (io.elementary.switchboard:21725): DEBUG: 22:23:51.457: LocaleManager.vala:131: setting system-wide locale via localectl
```
**appstream refresh:**
```
~ $ sudo appstreamcli refresh-cache --force --verbose
** (appstreamcli:21476): DEBUG: 22:20:22.663: Opening cache file: /tmp/appstream-cache-GHHVC0.mdb
** (appstreamcli:21476): DEBUG: 22:20:22.667: Added /usr/share/app-info/yaml to YAML metadata search path.
** (appstreamcli:21476): DEBUG: 22:20:22.668: Added /var/lib/app-info/yaml to YAML metadata search path.
** (appstreamcli:21476): DEBUG: 22:20:24.879: Refreshing AppStream cache
** (appstreamcli:21476): DEBUG: 22:20:24.880: Opening cache file: /var/cache/app-info/cache/tr.cache
** (appstreamcli:21476): DEBUG: 22:20:24.883: Cache set to floating mode.
** (appstreamcli:21476): DEBUG: 22:20:24.883: Searching for data in: /usr/share/app-info/yaml
** (appstreamcli:21476): DEBUG: 22:20:24.883: Searching for data in: /var/lib/app-info/yaml
** (appstreamcli:21476): DEBUG: 22:20:24.884: Reading: /usr/share/app-info/yaml/pantheon_bionic-extra_amd64.yml.gz
** (appstreamcli:21476): DEBUG: 22:20:24.885: Reading: /usr/share/app-info/yaml/pantheon_bionic-main_amd64.yml.gz
** (appstreamcli:21476): DEBUG: 22:20:24.959: Reading: /var/lib/app-info/yaml/packages.elementary.io_appcenter_dists_bionic_main_dep11_Components-amd64.yml.gz
** (appstreamcli:21476): DEBUG: 22:20:25.095: Reading: /var/lib/app-info/yaml
....................
....................
** (appstreamcli:21476): DEBUG: 22:20:27.018: Stemming language is: tr
(null)
~ $
```
**appstream status:**
```
~ $ sudo appstreamcli status --verbose
AppStream Durumu:
Sürüm: 0.12.9

Dağıtım üst verisi:
 /usr/share/app-info
  - YAML: 2
  - Simge Kümeleri:
     elementary-bionic-extra
     elementary-stable-bionic-main

 /var/lib/app-info
  - YAML: 11
  - Simge Kümeleri:
     ubuntu-bionic-main
     ubuntu-bionic-universe
     ubuntu-bionic-multiverse
     appcenter-bionic-main
     ubuntu-bionic-security-main
     ubuntu-bionic-security-universe
     ubuntu-bionic-security-multiverse
     ubuntu-bionic-updates-main
     ubuntu-bionic-updates-universe
     ubuntu-bionic-updates-multiverse
     ubuntu-bionic-backports-universe

 /var/cache/app-info
  - Boş.

Üst veri dosyaları:
  - 60 bileşen bulundu.
  - Eski veriyollarında 5 bileşen bulundu.

Özet:
** (appstreamcli:21419): DEBUG: 22:19:06.028: Opening cache file: /tmp/appstream-cache-EZI4C0.mdb
** (appstreamcli:21419): DEBUG: 22:19:06.030: Added /usr/share/app-info/yaml to YAML metadata search path.
** (appstreamcli:21419): DEBUG: 22:19:06.030: Added /var/lib/app-info/yaml to YAML metadata search path.
** (appstreamcli:21419): DEBUG: 22:19:06.031: Opening cache file: /tmp/appstream-cache-F0G4C0.mdb
** (appstreamcli:21419): DEBUG: 22:19:06.031: Cache set to floating mode.
** (appstreamcli:21419): DEBUG: 22:19:06.031: System cache is stale, ignoring it.
.................
.................
** (appstreamcli:21419): DEBUG: 22:19:08.233: Stemming language is: tr
Üst veri havuzunu yüklerken hata: Unable to add data: MDB_BAD_VALSIZE: Unsupported size of key/DB name/data, or wrong DUPFIXED size
~ $
```
_Last line in english_:
```
Error while loading the metadata pool: Unable to add data: MDB_BAD_VALSIZE: Unsupported size of key/DB name/data, or wrong DUPFIXED size
```

## Platform Information
```console
~ $ dpkg-query --showformat='${Package}:\t${Version}\n' --show appstream appcenter appstream-data-pantheon switchboard-plug-locale
appcenter:	3.2.1+r2106+pkg83~ubuntu5.0.1
appstream:	0.12.9-1+elementary11~ubuntu5.1.1
appstream-data-pantheon:	5.0-0+r82~ubuntu5.1.1
switchboard-plug-locale:	2.5.0+r588+pkg569~ubuntu5.0.1
~ $ head -2 /etc/os-release
NAME="elementary OS"
VERSION="5.1 Hera"
~ $ locale
LANG=tr_TR.UTF-8
LANGUAGE=tr
LC_CTYPE="tr_TR.UTF-8"
LC_NUMERIC=tr_TR.UTF-8
LC_TIME=tr_TR.UTF-8
LC_COLLATE="tr_TR.UTF-8"
LC_MONETARY=tr_TR.UTF-8
LC_MESSAGES="tr_TR.UTF-8"
LC_PAPER=tr_TR.UTF-8
LC_NAME=tr_TR.UTF-8
LC_ADDRESS=tr_TR.UTF-8
LC_TELEPHONE=tr_TR.UTF-8
LC_MEASUREMENT=tr_TR.UTF-8
LC_IDENTIFICATION=tr_TR.UTF-8
LC_ALL=
```
- [X] I'm using the latest released stable version

**Comment by queeup** [comment]
@danrabbit please take a look of this bug. Its quite urgent.

**Comment by queeup** [comment]
I tried Kubuntu 19.10 and unfortunately same issue occurred there also. It means this is not elementary or AppCenter specific issue.

**Comment by cassidyjames** [comment]
@queeup you could try reporting it on AppStream: https://github.com/ximion/appstream/

**Comment by queeup** [comment]
I will wait the new version of appstream and test it before closing this.

**Comment by cassidyjames** [comment]
@tintou is it worth backporting appstream for this? AppCenter is apparently very broken in Turkish otherwise. We may also be able to better handle an error according to https://github.com/ximion/appstream/issues/264#issuecomment-570787579, but I don't think that we would be able to rebuild AppStream's internal cache or anything—we could just tell Turkish users why their AppCenter is next to useless. :stuck_out_tongue:

**Comment by ximion** [comment]
@queeup The release is out now. If your distribution is too slow with updating, using the Debian `unstable` packages may work (https://packages.debian.org/source/sid/appstream - you'll need `libappstream4` as well as `appstream`). Ubuntu Focal should pull this into its repository soonish as well.
@cassidyjames Maybe a useful hint for you: The new AppStream 0.12.10 release pairs well with the also recently updated `packagekit >= 1.1.13-2` Debian package. Together, they fix an issue which causes AppStream to always load with dead caches on certain locale configurations, causing slower load times for some users and especially on software centers that don't asynchronously load the AsPool.

**Comment by ximion** [comment]
@queeup The release is out now. If your distribution is too slow with updating, using the Debian `unstable` packages may work (https://packages.debian.org/source/sid/appstream - you'll need `libappstream4` as well as `appstream`). Ubuntu Focal should pull this into its repository soonish as well.
@cassidyjames / @tintou Maybe a useful hint for you: The new AppStream 0.12.10 release pairs well with the also recently updated `packagekit >= 1.1.13-2` Debian package. Together, they fix an issue which causes AppStream to always load with dead caches on certain locale configurations, causing slower load times for some users and especially on software centers that don't asynchronously load the AsPool.

**Comment by tintou** [comment]
Thanks @ximion I'm not going to use the appstream release "as is" unfortunately as it requires a lot of new packages/backports regarding the D lang support. Until now I've done a few backport of commits here https://github.com/elementary/os-patches/commits/appstream-bionic-patched I'm going to cherry-pick some new one to fix this issue (and any other issue that the new release fixes). Thanks for all :slightly_smiling_face:

**Comment by ximion** [comment]
@tintou AppStream is easily backportable even to the old Debian stable release. It also doesn't depend on anything D-related. You are probably confusing it with the appstream-generator tool, which doesn't have anything to do with this bug.
On second look, does the older asgen maybe conflict with a new libappstream version? That may actually by the case in case the old asgen is really old. In this case you would probably benefit greatly from upgrading that one as well... (at least on the server, on clients asgen doesn't matter. And the data it generates should be compatible with every libappstream released in the past 6 years)

**Comment by cassidyjames** [comment]
We're now shipping the new appstream, so this should be resolved! Thanks everyone!
