### ISSUE TITLE
Alt-Shift works only one way

### ISSUE THREAD

**Issue by Mennaruuk** [elementary/triage#63]
The shortcut only works one-way. That is, if I had English and clicked Alt+Shift to switch to Spanish, it sure works, but when I click it again, it doesn't switch back to English. Important to note this happens on basically every distro I’ve been on, including Pop OS and Linux Mint.

**Comment by jeremypw** [comment]
This is fixed in Odin (elementary 6 unreleased) - I assume you are using Hera (elementary 5)?

**Comment by Mennaruuk** [comment]
Correct. Thank you so much!!!

**Comment by jeremypw** [comment]
Closing as fixed in Odin and a fix is unlikely to backported to Hera.
