### ISSUE TITLE
Issue with the latest update release of Elementary 8

### ISSUE THREAD

**Issue by inajmi** [elementary/triage#665]
### Discussed in https://github.com/orgs/elementary/discussions/664

<div type='discussions-op-text'>

<sup>Originally posted by **inajmi** December 23, 2024</sup>
after installing the latest updates available for elementary 8.0 the networking stops and it is not able to get an IP from the DHCP server nor will it work after defining a static IP address even. 

Please do let me know what logs do you require. </div>

**Comment by inajmi** [comment]
![image](https://github.com/user-attachments/assets/a0d8738c-d7a5-41f7-93fc-a8efb8f0fa70)


![image](https://github.com/user-attachments/assets/a1d1cd90-8da5-4515-9fac-d26c77d618fa)

**Comment by ryonakano** [comment]
Closing in favor of the original discussion :)
