### ISSUE TITLE
Turkish language plural formula is wrong on weblate translation website

### ISSUE THREAD

**Issue by queeup** [elementary/triage#68]
## What Happened

Turkish language plural formula is `n != 1` but some projects have a wrong plural formula.

https://l10n.elementary.io/languages/tr/#information

## Expected Behavior

All Turkish language projects have to be `n != 1` plural formula.

**Comment by tintou** [comment]
I've modified the rule in Weblate, this will be reflected when a translation is changed in a project

**Comment by queeup** [comment]
May I ask another question without opening a new issue?

There is two different Turkish translation for website. Which on is the correct one? All projects are `tr`, website is `tr`& `tr_TR`
https://l10n.elementary.io/languages/tr/website/
https://l10n.elementary.io/languages/tr_TR/website/

**Comment by queeup** [comment]
@tintou I am going to close this issue. Could you please answer my last question?

**Comment by tintou** [comment]
It looks like the one in use is tr_TR when looking at the language code in the website URL

**Comment by queeup** [comment]
Is it possible to use just tr and drop tr_TR? It's just confuses translaters.

**Comment by tintou** [comment]
See https://github.com/elementary/website/issues/2752
