### ISSUE TITLE
Odin iso fails to boot on lots of Dell hardware (and others)

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/triage#74]
This is an upstream bug experienced on a variety of Dell hardware, and sometimes others. This issue is for tracking the upstream issue and as a place to collate similar reports. Here's the launchpad issue:

https://bugs.launchpad.net/ubuntu/+source/shim/+bug/1937115

**Note:** This particular issue only affects booting from the live-media and does not affect the installed system. So if you use one of the workarounds, you only have to apply it once to get the install media to boot, then the installed system will work fine.

## Description

Booting the Odin iso on this hardware results in the following EFI errors being printed to the screen and the boot process failing:
```
Failed to open \EFI\BOOT\*garbled character* - Invalid Parameter
Failed to open \EFI\BOOT\*garbled character*: Invalid Parameter
start_image() returned Invalid Parameter
```

Looks like this:
![PXL_20210806_134052804](https://user-images.githubusercontent.com/3372394/128524257-5f25ca0e-596e-4d30-855e-6bbbd2729d0d.jpg)

### Workaround 1

The easiest workaround (if you're happy disabling secure boot) is to follow these steps (provided by @friimaind):

- Go to BIOS
- On the left click on General > Boot Sequence > Add Boot Option
- Insert what you want inside "Boot Option Name", like "Odin"
- click on "..." in "File Name" and select the USB Pen Drive and EFI / Boot / grubx64.efi
- Click OK to add the new boot option
- with the arrow up/down you can set this boot option as the first one

If you can't identify the USB Pen Drive you can connect / disconnect and see what changes inside "File Name" > "..." menu

After performing these steps and installing elementary OS, it _should_ be possible to re-enable secure boot if desired.

This workaround wasn't possible for some reason on my XPS 13 9343, as the USB stick wouldn't show as an option in the file chooser, so if you experience this, you may have to try one of the other workarounds.

### Workaround 2

If you are unable to disable secure boot, or the previous workaround doesn't work, the next best option is to download an Ubuntu 20.04.2 iso and copy the EFI folder from it to the elementary media (overwriting the original EFI files).

Whether this is possible depends on how the iso has been written to the USB media as sometimes it is left in a read-only state. If you are able, you can manually format the USB stick as FAT32 with a GPT partition table, then copy the files to it from within the elementary iso. Then you should be able to replace the EFI folder with an Ubuntu one afterwards.

Using this workaround should allow secure boot to function correctly.

### Workaround 3

The final workaround is to disable UEFI/enable legacy boot (sometimes called "Enable CSM"). Only use this workaround as a last resort as it may have the following consequences which you should understand and consider before continuing:

- Any other operating systems installed on the computer that you intend to keep (i.e. dual boot with your new elementary installation) may fail to boot after enabling legacy BIOS mode.
- You will have to change your disk's partition table to MBR instead of GPT which again may cause data loss or failure to boot of other operating systems.
- Secure boot will not be possible.
- Boot times may be slightly longer.
- It may not be possible to install other operating systems that are UEFI-only while legacy mode is enabled.

## Cause

Because the elementary iso was built after Ubuntu pushed a new `shim-signed` package, the shim included on the elementary iso is newer than that contained on the Ubuntu iso. This newer version of `shim-signed` appears to have issues on my particular hardware (and maybe others). I can also reproduce this issue with a vanilla Ubuntu Impish daily build, which appears to be using a similar `shim-signed` version.

**Comment by davidmhewitt** [comment]
My bug got marked as a duplicate of this one so I've updated my original comment:
https://bugs.launchpad.net/ubuntu/+source/shim/+bug/1937115

Sounds like this is happening on quite a few different Dell models, and is blocking the Ubuntu 20.04.3 release because they don't want to release a new iso with a shim that doesn't boot properly on a bunch of hardware.

**Comment by bluesabre** [comment]
On my 2013 Asus laptop, I'm seeing something similar with the 20210805 RC.

```
Invalid image
Failed to read header: Unsupported
Failed to load image: Unsupported
start_image() returned Unsupported
```

I believe this is the same issue.

**Comment by davidmhewitt** [comment]
> On my 2013 Asus laptop, I'm seeing something similar with the 20210805 RC.
> 
> ```
> Invalid image
> Failed to read header: Unsupported
> Failed to load image: Unsupported
> start_image() returned Unsupported
> ```
> 
> I believe this is the same issue.

If you get chance, could you try booting an Ubuntu impish daily iso and see if you get the same result? If you do, that will at least confirm it's not our iso build process causing this on your hardware.

Reading the Ubuntu bug report, I suspect that's actually a different problem but likely also caused by the newer version of shim.

**Comment by bluesabre** [comment]
@davidmhewitt Yep! Just tried today's impish image and I'm getting the same exact error.

**Comment by cassidyjames** [comment]
Am I correct that another potential workaround may be to disable UEFI mode in your device’s BIOS? I’m seeing some folks mention that in social media at least.

**Comment by o-alquimista** [comment]
> Am I correct that another potential workaround may be to disable UEFI mode in your device’s BIOS? I’m seeing some folks mention that in social media at least.

I just tried that one and it didn't go so well over here. Too many settings must be changed in the BIOS to be able to boot the installer (disable PTT, disable secure boot, enable legacy boot mode). Even after a successful installation I was unable to boot into the installed OS (no bootable media error). It's a Dell Inspiron 15 3000 series.

**Comment by o-alquimista** [comment]
@davidmhewitt  How do you mount the elementary installer media for read/write? It won't let me mount it, it says it's write-protected. I'm trying your workaround.

UPDATE: I got it. Thanks. GPT + FAT32 partition, copied everything and applied the workaround. Installation successful here :D

**Comment by davidmhewitt** [comment]
@o-alquimista I think that depends on how it's been written to the media. Some disk flashing tools create a FAT32 partition and copy the files from inside the ISO, others just copy it as an ISO filesystem, which is read-only.

You could manually format your USB as FAT32 and copy the files from the ISO, then replace the EFI ones. You may have to make sure the USB has a GPT partition table too.

**Comment by davidmhewitt** [comment]
Another workaround that I believe is working for some people is to manually add a boot entry in the BIOS/UEFI configuration. Adding a boot entry and manually selecting the `\EFI\BOOT\bootx64.efi` file on the USB stick or in some cases `\EFI\BOOT\grubx64.efi` is working for some.

This didn't work on my laptop, but it does have an older firmware where this may not be possible.

**Comment by bluesabre** [comment]
> Am I correct that another potential workaround may be to disable UEFI mode in your device’s BIOS? I’m seeing some folks mention that in social media at least.

After enabling "Launch CSM", the installer managed to boot. My first attempt to install with a custom partition layout failed because the installer couldn't select an ESP partition and grub couldn't find /boot/EFI. My second attempt, doing a full-disk installation worked correctly.

**Comment by bluesabre** [comment]
> @o-alquimista I think that depends on how it's been written to the media. Some disk flashing tools create a FAT32 partition and copy the files from inside the ISO, others just copy it as an ISO filesystem, which is read-only.
> 
> You could manually format your USB as FAT32 and copy the files from the ISO, then replace the EFI ones. You may have to make sure the USB has a GPT partition table too.

This worked for me. I also marked the partition as bootable with gparted just to play it safe.

**Comment by kryptoatom** [comment]
I had issue installing on HP spectre. Enabling Legacy Boot option worked for me.

**Comment by tomshoo** [comment]
> Enabling Legacy Boot option worked for me

After booting into legacy mode the ISO booted for me but the installer failed while installing grub for `x86_64` hardware.
My Workaround was to manually add a boot entry in the UEFI configuration pointing to `EFI\boot\grubx64.efi` present on the live ISO.

I have a DELL VOSTRO-13 series laptop

Update: If the above method does not work you can also try using [Ventoy](https://github.com/ventoy/Ventoy) and see if that works. For me the ISO booted up correctly although I did not try the installation.

**Comment by friimaind** [comment]
I had the same problem with my Dell XPS 9570. 
I managed to start the installer by entering the bios and creating a new "boot option":

- Go to BIOS
- On the left click on General > Boot Sequence > Add Boot Option
- Insert what you want inside "Boot Option Name", like "Odin"
- click on "..." in "File Name" and select the USB Pen Drive and EFI / Boot / grubx64.efi
- Click OK to add the new boot option
- with the arrow up/down you can set this boot option as the first one

If you can't identify the USB Pen Drive you can connect / disconnect and see what changes inside "File Name" > "..." menu

**Comment by davidmhewitt** [comment]
Thanks for the updates everyone, I've updated the original post with better details of the various workarounds.

Please comment only if you have new information to add to the issue. For example if you have this exact issue on some non-Dell hardware or you have further information not covered here about any of the workarounds.

The issue is being worked on upstream at Ubuntu and we'll be able to resolve this once they release a fixed version of the shim-signed package.

**Comment by Namelesske** [comment]
I tried all of the up mentioned possible solutions but not of them worked on my Dell Inspiron 3580

**Comment by miguelslp** [comment]
> On my 2013 Asus laptop, I'm seeing something similar with the 20210805 RC.
> 
> ```
> Invalid image
> Failed to read header: Unsupported
> Failed to load image: Unsupported
> start_image() returned Unsupported
> ```
> 
> I believe this is the same issue.

I also have the same experience on a Clevo n150sd

**Comment by cangulo** [comment]
Thanks for the workarounds @davidmhewitt . I had the same error with the Elementary OS 6 when installing it with Windows 10 on a Dell XPS 7590. I fix it following your workaround 1. Just one note, before booting from the USB, set the SATA Operation mode from RAID to AHCI in the BIOS.

**Comment by sklages** [comment]
Well, just a tiny info: I used **Workaround (1)** but after adding, rebooting and selecting the newly created option, it simply stops with black screen. Nothing happens, no keys are working, no textual output. -> Power button.
* Dell XPS 13 9380 / 4K 
* BIOS Rev. 1.10.0 / SATA Operation -> AHCI
* no dual boot, linux only
* sha256 checksum of ISO is okay

**Comment by danazkari** [comment]
> @davidmhewitt How do you mount the elementary installer media for read/write? It won't let me mount it, it says it's write-protected. I'm trying your workaround.
> 
> UPDATE: I got it. Thanks. GPT + FAT32 partition, copied everything and applied the workaround. Installation successful here :D

did it let you? I mounted that partition, tried copying over the files from the Ubuntu ISO but the partition size was too small and I wasn't able to resize the partition either. I feel like I'm so close!

**Comment by o-alquimista** [comment]
1. Give the device a GPT partition table, add a single FAT32 partition, then mount it through your file manager.

2. Mount both the elementary and the Ubuntu installer iso images (e.g. via GNOME Disks)

3. Copy and paste the entire contents of the mounted elementary image to your FAT32 partition.

4. Delete the EFI/ directory from your FAT32 partition. Replace it with the one from Ubuntu.

Enviado via ProtonMail móvel

-------- Mensagem Original --------
Ativo 13 de ago de 2021 09:51, Daniel Prado escreveu:

**Comment by LuisMi1245** [comment]
**And what about those computers that only support legacy BIOS mode?**

I've tried everything (even wiping the entire hard drive and letting Elementary 6 do its thing) and just starting the installation, it just tells me this: `errored while installing system; hostname is not valid.`

I did not find any similar case that would allow me to solve this installation problem. My computer is old but it is "64 bits". 
(I used Balena Etcher to create the bootable usb.)

**Comment by davidmhewitt** [comment]
> **And what about those computers that only support legacy BIOS mode?**
> 
> I've tried everything (even wiping the entire hard drive and letting Elementary 6 do its thing) and just starting the installation, it just tells me this: `errored while installing system; hostname is not valid.`
> 
> I did not find any similar case that would allow me to solve this installation problem. My computer is old but it is "64 bits". 
> (I used Balena Etcher to create the bootable usb.)

That's a different issue that's completely unrelated to this. Please open a new issue and include the installer log or a picture of it.

**Comment by gmontjr** [comment]
I'm having the EFI/boot/ Invalid parameter on a Dell 3880.
I'll try these workarounds since disabling Secure Boot didn't help.

**Comment by krisives** [comment]
> Am I correct that another potential workaround may be to disable UEFI mode in your device’s BIOS? I’m seeing some folks mention that in social media at least.

@cassidyjames Yes, but doing so likely means your system isn't going to function the way it really should, some drivers might not be have the same and (most importantly) transitioning a legacy boot installation to a UEFI installation for some users can be frustrating.

Until this gets resolved, as it stands, we have a `.iso` being served from the homepage that doesn't work for a significant number of users. Can we do one of these until it gets resolved?

* Revert the shim to a previous version
* Apply the copy operation of the EFI files from the stock Ubuntu that works

Obviously those are short-term workarounds until a real solution is found.

**Comment by Aleblazer** [comment]
> On my 2013 Asus laptop, I'm seeing something similar with the 20210805 RC.
> 
> ```
> Invalid image
> Failed to read header: Unsupported
> Failed to load image: Unsupported
> start_image() returned Unsupported
> ```
> 
> I believe this is the same issue.

Exact same issue on a Surface Pro 3, secure boot disabled.

**Comment by faelz** [comment]
I solved this problem using NTFS on Rufus. Don't use FAT. It worked perfectly.

**Comment by tomshoo** [comment]
> I solved this problem using NTFS on Rufus. Don't use FAT. It worked perfectly.

The problem with using NTFS is not all Dell Laptops detect it as a bootable device, especially the older ones like my Dell Vostro-13.

**Comment by RodrigoHahn** [comment]
Just for posterity, I solved it from another Ubuntu machine with:
`efibootmgr --create --label Blah --disk /dev/sdxn --loader "\EFI\boot\grubx64.efi"`

(customize accordingly)

**Comment by gmontjr** [comment]
I tried NTFS on my Dell 3880 and it did not see the thumb drive as a
bootable device. The PC does see a FAT-formatted thumb drive.

**Comment by Namelesske** [comment]
I see all the workarounds but someone could tell me exactly what is the root cause of the problem. Because other distros are working correctly. Namely Debian and Ubuntu.

**Comment by tomshoo** [comment]
@Namelesske From what I could gather from [this](https://bugs.launchpad.net/ubuntu/+source/shim/+bug/1937115), the same issue existed on `Ubuntu Impish Indri Daily` build. Apparently the reason is that the system is trying to read a file that does not even exist and does not go to fallback mode. The only thing weird is that this issue mostly exists on Dell Hardware, as apparent from the same issue I mentioned.

**Comment by Namelesske** [comment]
Similar issue in Fedora 
https://bugzilla.redhat.com/show_bug.cgi?id=1954245
https://bugzilla.redhat.com/show_bug.cgi?id=1955416

**Comment by geekyBoogiepop** [comment]
Seems it is already fixed. Please release a new ISO 🙏 I haven't been able to install it on my laptop too.
https://bugs.launchpad.net/ubuntu/+source/shim/+bug/1937115

**Comment by davidmhewitt** [comment]
You can see on the launchpad page, that the status for Ubuntu Focal (on which Odin is based) is not yet "Fix Released", meaning the fix is not yet available.

We will release a new iso when the fix has been released, after we've had chance to build a new iso and test it.

I have hardware I can reproduce this issue on and I know it's affecting a lot of users, so rest assured it will be released as soon as is practical.

**Comment by Namelesske** [comment]
That’s straight talking, thanks a lot.

**Comment by danazkari** [comment]
> You can see on the launchpad page, that the status for Ubuntu Focal (on which Odin is based) is not yet "Fix Released", meaning the fix is not yet available.
> 
> We will release a new iso when the fix has been released, after we've had chance to build a new iso and test it.
> 
> I have hardware I can reproduce this issue on and I know it's affecting a lot of users, so rest assured it will be released as soon as is practical.

![image](https://user-images.githubusercontent.com/349542/130171140-8d3614ab-9d16-4a02-b439-c4030ea0453e.png)

seems like it is now! :tada: Thank you for being so straight forward with this issue, for the better part of the day that Odin was released I thought it was an issue with my machine and that I was... helically wrapped around an inclined plane.

**Comment by geekyBoogiepop** [comment]
Alright, now we just need a new ISO, I was so sad when I tried everything and nothing worked 😭

**Comment by cassidyjames** [comment]
I'm working on getting a new daily build to test, and if all goes well there, we can spin a new stable ISO.

**Comment by cassidyjames** [comment]
And updated daily build is now up on [Early Access](https://builds.elementary.io/); @davidmhewitt you'd mentioned giving that a try today, I think.

**Comment by krisives** [comment]
It seems kind of strange to keep a `.iso` on the frontpage of `elementary.io` that is broken for a large amount of users and to put the working one behind an Early Access paywall.

**Comment by geekyBoogiepop** [comment]
They are testing it before public. Not even Ubuntu or any other distro has released a new ISO yet. This package was affecting almost all distributions.

**Comment by davidmhewitt** [comment]
I can confirm that the latest daily iso boots perfectly in UEFI mode on my previously affected Dell laptop.

Given that and the large number of confirmations in the Ubuntu ticket, I think we should be good to go with preparing a new stable iso @cassidyjames 

It'll probably take us a few more days to build it and verify it on some other hardware combinations, but we're getting close.

**Comment by ma-he-sh** [comment]
> 
> 
> I had the same problem with my Dell XPS 9570.
> I managed to start the installer by entering the bios and creating a new "boot option":
> 
>     * Go to BIOS
> 
>     * On the left click on General > Boot Sequence > Add Boot Option
> 
>     * Insert what you want inside "Boot Option Name", like "Odin"
> 
>     * click on "..." in "File Name" and select the USB Pen Drive and EFI / Boot / grubx64.efi
> 
>     * Click OK to add the new boot option
> 
>     * with the arrow up/down you can set this boot option as the first one
> 
> 
> If you can't identify the USB Pen Drive you can connect / disconnect and see what changes inside "File Name" > "..." menu

I can confirm that this solution suggested by @friimaind  works for my Dell XPS 9570 for elementary os. I got the same boot issue when I try to install Ubuntu 21.04.

**Comment by mcclurgm** [comment]
While this is building, should we put a notice somewhere (like the download page?) that there's a known issue and a fix is coming? I expect that just seeing a non bootable disk would discourage many people, potentially some of which have already paid. Hopefully that would keep more users by informing them that they'll be able to boot soon than it would lose by forgetting to check back when the fix is released...

I'll admit that I had this issue and was very confused for a while, and the things I saw on duckduckgo/google suggested I do some potentially unsafe things before I found this bug report. I'm going to wait until the new fix is out, but I would have personally appreciated a warning. Since the fix is already building with end in sight, some sort of notice shouldn't be too terrible to add imo.

**Comment by cassidyjames** [comment]
@mcclurgm we added [the FAQ](https://github.com/elementary/os/wiki/elementary-OS-6-Odin-FAQ#why-wont-the-installer-or-os-boot-on-my-hardware) to the homepage, the announcement blog post, the installation instructions, and social media which mentions this specific issue (along with a handful of other very common questions people have).

**Comment by mcclurgm** [comment]
😬 I definitely should have noticed that... my bad.

**Comment by DavidVujic** [comment]
Workaround 1 solved it for me, I'm running a Dell XPS 13 from 2017 and succeed with a clean install of Elementary OS 6. Thank you!

**Comment by cassidyjames** [comment]
Alright, prepping a new stable ISO, now! 

- Release tag: https://github.com/elementary/os/releases/tag/6.0-20210823
- CI: https://github.com/elementary/os/runs/3404077980

**Comment by rafaelcn** [comment]
@cassidyjames, the build has failed and when I try to download on the website, the last version has the date 20210810.

**Comment by cassidyjames** [comment]
@rafaelcn the stable action succeeded. We are prepping the download still; we'll announce on social media and on the release tag once it is available for download.

**Comment by rafaelcn** [comment]
Is there any way to download it as it is? Are you guys stalling for the 6.0.1 of Odin?

**Comment by cassidyjames** [comment]
The "prepping" includes uploading and propagating it across global CDNs so we don't overload a single download server. We're not "stalling", but the release process simply takes time. We will update when it is available for download.

**Comment by cassidyjames** [comment]
The updated ISO is now available at [elementary.io](https://elementary.io). The download file is named `elementaryos-6.0-stable.20210823.iso` with a SHA256 sum of `24e7ac95526d24ebab6e725078448143ae30106d96ab51c44f475c654a3e5d56 `. 

As always, more info about installing (including verifying the SHA256 sum) can be found at [elementary.io/docs/installation](https://elementary.io/docs/installation)
