### ISSUE TITLE
Odin New User Creation Loop

### ISSUE THREAD

**Issue by iancleary** [elementary/triage#75]
## What Happened
Installed elementary OS 6 Odin installation onto Framework Laptop.  The installation was successfull (rebooted without USB media) and I was able to create my `iancleary` user.  After using the initial session successfully for about 15 minutes, I restarted and was shown the new user creation wizard.

I was able to make a `test` user with a password, and login to that user.  I'm able to repeatably login and logout of the test user, but the `iancleary` user is not shown in the greeter, but the `/home/iancleary` directory still exists.

## Expected Behavior

I was expecting the greeter to show the `iancleary` user and be able to login as that user.  After logging in, I would expect to be able to reboot and come back to the greeter with a card widget prompting me to login as the `iancleary` user.

## Steps to Reproduce

1. Install first user 
2. Reboot
3. If new user wizard is displayed, create `test` user (or 2nd name)
4. Reboot or log out
5. Check if able to see first user (`iancleary` in my case)

> I'm not sure what specific configuration (hardware) is required to reproduce the above behavior, but I've performed a clean installation twice today with the same results.  

### Logs

```bash
test@Laptop-ccf50e94:/home$ ll
total 16
drwxr-xr-x  4 root      root      4096 Aug 11 03:26 ./
drwxr-xr-x 18 root      root      4096 Aug 11 00:53 ../
drwxr-xr-x 18 iancleary iancleary 4096 Aug 11 03:33 iancleary/
drwxr-xr-x 15 test      test      4096 Aug 11 03:39 test/
```

I'm not sure how to get the greeter or lightdm logs, but would be happy to get them if shown how.

### Software
- elementary OS 6 Odin
- Built on Ubuntu 20.04.2 LTS
- Linux 5.11.0-25-generic

> Is the fact that we are not on Ubuntu 20.04.3 LTS an issue?  
> See [Cassidy's post on the community.frame.work site](https://community.frame.work/t/using-elementary-os-on-the-framework-laptop/4453) discussing Ubuntu 20.04.3

### Hardware
- Quad-Core 11th Gen Intel® Core™ i7-1165G7 @ 2.80GHz
- Intel®
- Memory: 32GB (2 x 16GB) DDR4-3200
- WiFi: Intel® Wi-Fi 6E AX210 No vPro®
- Storage: 979.1 GB storage (1TB - WD_BLACK™ SN850 NVMe™)

### Steps take post clean install

I maintain some installation scripts for Ubuntu that I use to setup various software in a repeatable way. 

https://github.com/iancleary/ubuntu-dev-playbook 

While I don't believe they are an issue, but I believe it falls under the "unconventional setups" category in the issue template.

**Comment by iancleary** [comment]
After running some commands from https://github.com/iancleary/ubuntu-dev-playbook, I was able to replicate the issue where a user disappears from the greeter. 

I'm not sure if that's the root cause or not, but another data point for that portion of the fishbone. I'll see if I can isolate it further.

**Comment by cassidyjames** [comment]
@iancleary yeah hm. I'm unable to reproduce your issue directly on my Framework Laptop, but I'm also not running your Ansible stuff; I imagine something in there is modifying an important dotfile, and then that's failing to load the session?

**Comment by iancleary** [comment]
![image](https://user-images.githubusercontent.com/9398410/129089288-ac75591a-a644-4acb-ac0c-33c98e39f1b6.jpeg)

**Comment by iancleary** [comment]
@cassidyjames I discovered the issue!  Thank you for your attempt at replication and the article on supporting the Framework laptop.

-------

It's an issue with my configuration that causes the users shell to not be set properly.

# Root Cause
Part of https://github.com/iancleary/ansible-role-zsh/blob/823fe8bc1e603016030553aa36baf3d96cc1a945/tasks/configure-zsh.yml#L2-L6 sets the default shell for the user as `/bin/sh``.  This probably was what is was for Ubuntu 20.04 when I made the role.  That assumption is not one to make.

## Location of zsh in elementary OS

```bash
test@Laptop-5160c37a:~/ubuntu-dev-playbook$ which zsh
/usr/bin/zsh
```

## Bad default shell path
> `/usr/bin/zsh` is not `/bin/zsh`

I am guessing the session tries to spawn the default shell, then cannot find `/bin/zsh`.  This in turn likely blocks the user session from loading.  More conjecture on what happens next: that makes that user not show up in the greeter application, even though the `/home` directory shows that user.

## Testing the Fix.

With my `test` user created, I ran `sudo chsh -s /usr/bin/zsh iancleary` and am able to have that user appear in the greeter again.

![image](https://user-images.githubusercontent.com/9398410/129089288-ac75591a-a644-4acb-ac0c-33c98e39f1b6.jpeg)

## Conclusion

The error was on my configuration, and I do not believe there is a request for the elementary team (unless you see something I don't), but I think it's pretty clear I caused the unexpected behavior with a bad assumption on the zsh path being a specific value across distributions.

**Comment by iancleary** [comment]
I'm closing this as a user error, per https://github.com/elementary/triage/issues/75#issuecomment-897083661

Thanks for the help!
