### ISSUE TITLE
AppCenter disfunction

### ISSUE THREAD

**Issue by dimidalli** [elementary/triage#80]
The last two or three days, it doesn't show me the installed list, and appears a "Failed to Fetch Updates".
In few words:
"This may have been caused by external, manually added software repositories or a corrupted sources file".

And in details:
E: Problem parsing dependency 53
E: Error occurred while processing python3-gnocchi (NewVersion2)
E: Problem with MergeList /var/lib/apt/lists/gr.archive.ubuntu.com_ubuntu_dists_bionic_universe_binary-i386_Packages
E: The package lists or status file could not be parsed or opened

I have no idea what is all about, and of course no idea how to fix it.
Any suggestions would be appreciated.
Dimi

**Comment by dimidalli** [comment]
Thank you for your interest, but I finally did a format, and reinstall the elementary OS Hera. It was necessary after two years anyway...
I was trying to install a browser, which I don't even remember... - I prefer to forget :) - maybe the waterfox...palemoon...I'm not sure...
But lately I tried also to install dictionaries, so probably one of these actions was "wrong". I'm a simple user after all...
Thank you very much once more

**Comment by cassidyjames** [comment]
@dimidalli thanks for the update! I'll go ahead and close this since it seems like the original issue is resolved or no longer reproducible.
