### ISSUE TITLE
the top bar (wingpanel) it's looking like sliced

### ISSUE THREAD

**Issue by P-dos-Santos** [elementary/triage#9]
In the latest actualization of elementary occoring a bug with wingpanel. Now it's looking like this:

![Captura de tela de 2020-01-17 21-55-53](https://user-images.githubusercontent.com/16929155/72655577-2bad7900-3974-11ea-95e7-c62104039fa7.png)

**Comment by P-dos-Santos** [comment]
My system info maybe helpfull...



santos@RV415:~$ sudo inxi -Fxz
System:    Host: RV415 Kernel: 5.3.0-26-generic x86_64 bits: 64 gcc: 7.4.0 Console: tty 0
           Distro: elementary OS 5.1 Hera
Machine:   Device: laptop System: SAMSUNG product: RV415 v: P07RAT serial: <filter>
           Mobo: SAMSUNG model: NP-RV415-CD3BR v: SEC_SW__1234567890ABCD serial: <filter>
           BIOS: American Megatrends v: P07RAT.039.130423.KK date: 04/23/2013
Battery    BAT1: charge: 9.9 Wh 98.0% condition: 10.1/31.7 Wh (32%) model: SAMSUNG SR Real status: N/A
CPU:       Dual core AMD E-300 APU with Radeon HD Graphics (-MCP-) arch: Bobcat rev.0 cache: 512 KB
           flags: (lm nx sse sse2 sse3 sse4a ssse3 svm) bmips: 5189
           clock speeds: max: 1300 MHz 1: 794 MHz 2: 831 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Wrestler [Radeon HD 6310] bus-ID: 00:01.0
           Display Server: X.Org 1.20.5 drivers: ati,radeon (unloaded: modesetting,fbdev,vesa)
           Resolution: 1366x768@60.01hz
           OpenGL: renderer: AMD PALM (DRM 2.50.0 / 5.3.0-26-generic, LLVM 9.0.0)
           version: 3.3 Mesa 19.2.1 Direct Render: Yes
Audio:     Card-1 Advanced Micro Devices [AMD/ATI] Wrestler HDMI Audio driver: snd_hda_intel bus-ID: 00:01.1
           Card-2 Advanced Micro Devices [AMD/ATI] SBx00 Azalia (Intel HDA)
           driver: snd_hda_intel bus-ID: 00:14.2
           Sound: Advanced Linux Sound Architecture v: k5.3.0-26-generic
Network:   Card-1: Qualcomm Atheros AR9285 Wireless Network Adapter (PCI-Express) driver: ath9k bus-ID: 03:00.0
           IF: wlp3s0 state: up mac: <filter>
           Card-2: Realtek RTL810xE PCI Express Fast Ethernet controller driver: r8169 port: e000 bus-ID: 05:00.0
           IF: enp5s0 state: down mac: <filter>
Drives:    HDD Total Size: 240.1GB (37.4% used)
           ID-1: /dev/sda model: KINGSTON_SUV400S size: 240.1GB temp: 38C
Partition: ID-1: / size: 220G used: 84G (41%) fs: ext4 dev: /dev/sda1
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 51.6C mobo: N/A gpu: 51.0
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 192 Uptime: 33 min Memory: 1345.0/3513.6MB Init: systemd runlevel: 5 Gcc sys: N/A
           Client: Shell (sudo) inxi: 2.3.56

**Comment by P-dos-Santos** [comment]
[inxi.txt](https://github.com/elementary/triage/files/4080680/inxi.txt)

**Comment by P-dos-Santos** [comment]
My system info maybe helpfull...

```System:    Host: RV415 Kernel: 5.3.0-26-generic x86_64 bits: 64 gcc: 7.4.0 Console: tty 0
           Distro: elementary OS 5.1 Hera
Machine:   Device: laptop System: SAMSUNG product: RV415 v: P07RAT serial: <filter>
           Mobo: SAMSUNG model: NP-RV415-CD3BR v: SEC_SW__1234567890ABCD serial: <filter>
           BIOS: American Megatrends v: P07RAT.039.130423.KK date: 04/23/2013
Battery    BAT1: charge: 9.9 Wh 98.0% condition: 10.1/31.7 Wh (32%) model: SAMSUNG SR Real status: N/A
CPU:       Dual core AMD E-300 APU with Radeon HD Graphics (-MCP-) arch: Bobcat rev.0 cache: 512 KB
           flags: (lm nx sse sse2 sse3 sse4a ssse3 svm) bmips: 5189
           clock speeds: max: 1300 MHz 1: 820 MHz 2: 782 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Wrestler [Radeon HD 6310] bus-ID: 00:01.0
           Display Server: X.Org 1.20.5 drivers: ati,radeon (unloaded: modesetting,fbdev,vesa)
           Resolution: 1366x768@60.01hz
           OpenGL: renderer: AMD PALM (DRM 2.50.0 / 5.3.0-26-generic, LLVM 9.0.0)
           version: 3.3 Mesa 19.2.1 Direct Render: Yes
Audio:     Card-1 Advanced Micro Devices [AMD/ATI] Wrestler HDMI Audio driver: snd_hda_intel bus-ID: 00:01.1
           Card-2 Advanced Micro Devices [AMD/ATI] SBx00 Azalia (Intel HDA)
           driver: snd_hda_intel bus-ID: 00:14.2
           Sound: Advanced Linux Sound Architecture v: k5.3.0-26-generic
Network:   Card-1: Qualcomm Atheros AR9285 Wireless Network Adapter (PCI-Express) driver: ath9k bus-ID: 03:00.0
           IF: wlp3s0 state: up mac: <filter>
           Card-2: Realtek RTL810xE PCI Express Fast Ethernet controller driver: r8169 port: e000 bus-ID: 05:00.0
           IF: enp5s0 state: down mac: <filter>
Drives:    HDD Total Size: 240.1GB (37.4% used)
           ID-1: /dev/sda model: KINGSTON_SUV400S size: 240.1GB temp: 42C
Partition: ID-1: / size: 220G used: 84G (41%) fs: ext4 dev: /dev/sda1
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 51.5C mobo: N/A gpu: 51.0
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 197 Uptime: 2:27 Memory: 1544.9/3513.6MB Init: systemd runlevel: 5 Gcc sys: N/A
           Client: Shell (sudo) inxi: 2.3.56 
```

**Comment by cassidyjames** [comment]
@P-dos-Santos does it always do this (reproducibly), or was it a one-time thing?

**Comment by P-dos-Santos** [comment]
This hapen

**Comment by P-dos-Santos** [comment]
This happens every time when I power my computer. See this link below to more details about the issue 
https://elementaryos.stackexchange.com/questions/22128/elementary-os-5-1-hera-tooltips-messed-up

**Comment by P-dos-Santos** [comment]
This happens every time when I power my computer. See this link below to more details about the issue 
https://elementaryos.stackexchange.com/questions/22128/elementary-os-5-1-hera-tooltips-messed-up

**Comment by danirabbit** [comment]
I'm going to close this issue as "Out of scope" for elementary OS since it sounds like an issue with the upstream Radeon driver.

**Comment by P-dos-Santos** [comment]
Ok. The Radeon driver has been updated. The problem was solved
