### ISSUE TITLE
Interpolated (smooth) scrolling

### ISSUE THREAD

**Issue by Mennaruuk** [elementary/triage#90]
### Problem

Windows and macOS has scrolling that is interpolated. When one flicks their mouse wheel, the scrolling bar accelerates before decelerating and stopping. Right now on elementary OS (and every Linux distro), scrolling is rigid. [Here](https://gitlab.gnome.org/GNOME/gtk/-/issues/702) is a link to a similar issue over at GNOME’s GitLab.

### Proposal

Implement interpolated (smooth) scrolling that is akin to that of Windows or macOS.

**Comment by cassidyjames** [comment]
This is something being worked on at a lower level than elementary OS, and will likely be included in a future upstream release of the Linux kernel, LibInput, and GTK. I don't think there is anything specific we can do here about it.

**Comment by cassidyjames** [comment]
Ah, I see that this is specifically about interpolation and not high resolution scrolling; in that case, it is solely a GTK concern as far as I understand, and that linked open issue on GTK is a better place to track it.
