### ISSUE TITLE
Desktop takes unusually long to load after update

### ISSUE THREAD

**Issue by swanux** [elementary/triage#93]
### What Happened?

After updating from the AppCenter (2021. Oct. 28) loading the desktop takes around 5-15 seconds of black screen (which wasn't the case before). I encounter this on both of my laptop and my PC.

### Steps to Reproduce

1. Boot up your machine
2. Login to your account
3. You'll see the black screen before the wallpaper appearing for 5-15 seconds

### Expected Behavior

Normal desktop initialization (around 2-5 seconds altogether, no significant black screen time period).

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Laptop:
- Lenovo IdeaPad 720
- Intel Core i5-8250U
- AMD Radeon RX 550 M
- 8GB DDR4 RAM

PC:
- Intel Core i5-4690K
- AMD Radeon RX 570 4GB
- 16GB DDR3 RAM

**Comment by davidmhewitt** [comment]
Have you fully updated again?

We saw this issue appear a few days ago and we were tracking it here: https://github.com/elementary/portals/issues/33

`io.elementary.portals` 1.0.1 with a fix for the issue was released around 16 hours ago.

**Comment by swanux** [comment]
My bad, that's right. Didn't expect an update to fix it so soon.
Now it's working fine.

**Comment by davidmhewitt** [comment]
Thanks for confirming, glad the fix is working for you!
